
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programCOMMA IDENT IS LPAREN NUMBER QMARK_LBRACK RBRACK RPAREN STRINGprogram : statementsstatements : statements statementstatements : statementstatement : IDENT IS valuevalue : atomvalue : arrayatom : NUMBERatom : STRINGatom : QMARK_LBRACK IDENT RBRACKarray : LPAREN RPARENarray : LPAREN array_elements RPARENarray_elements : valuearray_elements : array_elements COMMA value'
    
_lr_action_items = {'IDENT':([0,2,3,5,7,8,9,10,11,12,15,18,19,],[4,4,-3,-2,-4,-5,-6,-7,-8,14,-10,-9,-11,]),'$end':([1,2,3,5,7,8,9,10,11,15,18,19,],[0,-1,-3,-2,-4,-5,-6,-7,-8,-10,-9,-11,]),'IS':([4,],[6,]),'NUMBER':([6,13,20,],[10,10,10,]),'STRING':([6,13,20,],[11,11,11,]),'QMARK_LBRACK':([6,13,20,],[12,12,12,]),'LPAREN':([6,13,20,],[13,13,13,]),'RPAREN':([8,9,10,11,13,15,16,17,18,19,21,],[-5,-6,-7,-8,15,-10,19,-12,-9,-11,-13,]),'COMMA':([8,9,10,11,15,16,17,18,19,21,],[-5,-6,-7,-8,-10,20,-12,-9,-11,-13,]),'RBRACK':([14,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,5,]),'value':([6,13,20,],[7,17,21,]),'atom':([6,13,20,],[8,8,8,]),'array':([6,13,20,],[9,9,9,]),'array_elements':([13,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser_conf.py',12),
  ('statements -> statements statement','statements',2,'p_statements_multi','parser_conf.py',16),
  ('statements -> statement','statements',1,'p_statements_single','parser_conf.py',21),
  ('statement -> IDENT IS value','statement',3,'p_statement_const','parser_conf.py',25),
  ('value -> atom','value',1,'p_value_atom','parser_conf.py',37),
  ('value -> array','value',1,'p_value_array','parser_conf.py',41),
  ('atom -> NUMBER','atom',1,'p_atom_number','parser_conf.py',45),
  ('atom -> STRING','atom',1,'p_atom_string','parser_conf.py',49),
  ('atom -> QMARK_LBRACK IDENT RBRACK','atom',3,'p_atom_constref','parser_conf.py',53),
  ('array -> LPAREN RPAREN','array',2,'p_array_empty','parser_conf.py',64),
  ('array -> LPAREN array_elements RPAREN','array',3,'p_array_nonempty','parser_conf.py',68),
  ('array_elements -> value','array_elements',1,'p_array_elements_single','parser_conf.py',72),
  ('array_elements -> array_elements COMMA value','array_elements',3,'p_array_elements_many','parser_conf.py',76),
]
